version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
            - ./redis-volume:/data
        command: [ "redis-server", "/redis.conf" ]
    go:
        build: ./server
        ports:
          - "6969:6969"
    