version: '3'
services:
    kim:
        build: ./server
        ports:
          - "6969:6969"
        environment:
            - SERVER_ID=Kim
            - SERVER_PORT=6969
            - REDIS_PORT=6379
        volumes:
            - ./db/kim:/data/raft-db    
    ricky:
        build: ./server
        ports:
            - "6970:6970"
        environment:
            - SERVER_ID=Ricky
            - SERVER_PORT=6970
            - REDIS_PORT=6380     
        volumes:
            - ./db/ricky:/data/raft-db       
    laszlo:
        build: ./server
        ports:
            - "6971:6971"
        environment:
            - SERVER_ID=Laszlo
            - SERVER_PORT=6971
            - REDIS_PORT=6381
        volumes:
            - ./db/laszlo:/data/raft-db    